#!/bin/sh
set -e

# Variables 
appName="visParaflow"
appdir="/opt/$appName"

# Copy the app script file to /usr/local/bin
sudo mv $appdir/app.sh /usr/local/bin/$appName
sudo chmod +x /usr/local/bin/$appName

exit 0