name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # Enables manual trigger

jobs:
  # build-windows:
  #   runs-on: windows-latest

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v2

  #     - name: Set up CMake
  #       uses: lukka/get-cmake@latest

  #     - name: Set up Qt
  #       uses: jurplel/install-qt-action@v2
  #       with:
  #         version: '6.5.1'
  #         host: 'windows'
  #         target: 'desktop'
  #         arch: 'win64_msvc2019_64'

  #     - name: Configure CMake
  #       run: cmake -S . -B build

  #     - name: Build
  #       run: cmake --build build

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Set up Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '6.5.1'
          host: 'macos'
          target: 'desktop'
          arch: 'clang_64'

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build